name: Push changes to production
on: 
  push:
    branches:
      - master

jobs:
  update-production:
    name: Log into production server and pull changes
    runs-on: ubuntu-latest
    environment: production_environment
    steps: 
      - name: Set private and public keys
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Login and pull new master version
        run: ssh ${{ secrets.SSH_HOST }} "cd ${{ secrets.DEPLOYMENT_PATH }} && git checkout master && git pull -s recursive -X theirs --no-edit && composer install && php repair.php --instance ${{ secrets.DEPLOYMENT_PATH }}"

