name: Push changes to production
on: 
  push:
    branches:
      - master

jobs:
  update-production:
    name: Log into production server and pull changes
    runs-on: ubuntu-latest
    environment: production_environment
    steps: 
      - name: Set private and public keys
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/id_rsa
      - name: Login and pull new master version
        run: ssh ${{ secrets.SSH_HOST }} "cd ${{ secrets.DEPLOYMENT_PATH }} && git checkout master && git pull -s recursive -X theirs --no-edit && composer install && php repair.php --instance ${{ secrets.DEPLOYMENT_PATH }}"

